/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication13;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author borag
 */
public class addSales extends javax.swing.JFrame {

    /**
     * Creates new form addSales
     */
    public addSales() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        viewInput = new javax.swing.JButton();
        labelQuantity = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelpRICE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productId = new javax.swing.JTextField();
        productAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewInput.setText("view");
        viewInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInputActionPerformed(evt);
            }
        });
        getContentPane().add(viewInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 70, 20));

        labelQuantity.setText("jLabel7");
        getContentPane().add(labelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        labelName.setText("jLabel7");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        labelpRICE.setText("jLabel7");
        getContentPane().add(labelpRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel6.setText("Product details");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("←dashboard");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jButton2.setText("view sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jToggleButton1.setText("submit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("product id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_ecoshift-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Sales");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 20));
        getContentPane().add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, 30));

        productAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAmountActionPerformed(evt);
            }
        });
        getContentPane().add(productAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:5050/mydatabase",
                    "root",
                    ""
            );

            // select data 
            String query = "SELECT * FROM `productstable` WHERE `id` = ? ";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setInt(1, Integer.parseInt(productId.getText()));
            ResultSet res = statement.executeQuery();

            if (!res.next()) {
                JOptionPane.showMessageDialog(this, "no id " + productId.getText() + " found");
            }

            int totalQuantity = 0;

            System.out.print("hello");
            int initialQuantity = res.getInt("quantity");
            totalQuantity = initialQuantity - Integer.parseInt(productAmount.getText());

            if (totalQuantity <= 0) {
                JOptionPane.showMessageDialog(this, "out of stocks");
            }

            if (totalQuantity > 0) {
                String insertQuery = "INSERT INTO `productsales`(`id`, `quantity`) VALUES (?, ?)";
                PreparedStatement insertStatement = conn.prepareStatement(insertQuery);

                insertStatement.setInt(1, Integer.parseInt(productId.getText()));
                insertStatement.setInt(2, Integer.parseInt(productAmount.getText()));

                insertStatement.execute();
            }

            if (totalQuantity >= 0) {
                try {
                    String productQuery = "UPDATE productstable SET quantity = ? WHERE id = ?";
                    PreparedStatement productStatement = conn.prepareStatement(productQuery);
                    productStatement.setInt(1, totalQuantity);
                    productStatement.setInt(2, Integer.parseInt(productId.getText()));

                    productStatement.execute();

                    JOptionPane.showMessageDialog(this, "successfully sell");
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "failed on update");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed on selection");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void productAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productAmountActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new salesTrackingForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new dashboard("").setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void viewInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInputActionPerformed
        try {
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:5050/mydatabase",
                    "root",
                    ""
            );

            // select data 
            String query = "SELECT * FROM `productstable` WHERE `product name` = ? ";
            PreparedStatement statement = conn.prepareStatement(query);

            statement.setInt(1, Integer.parseInt(productId.getText()));
            ResultSet res = statement.executeQuery();

            if (res.next()) {
                   labelName.setText(res.getString("product name"));
                   labelName.setText(String.valueOf(res.getInt("product price")));
                   labelName.setText(String.valueOf(res.getInt("product quantity")));
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_viewInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelpRICE;
    private javax.swing.JTextField productAmount;
    private javax.swing.JTextField productId;
    private javax.swing.JButton viewInput;
    // End of variables declaration//GEN-END:variables
}
