/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication13;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author borag
 */
public class adminPanel extends javax.swing.JFrame {

    /**
     * Creates new form adminPanel
     *
     *
     */
    public void callUserList() {
        try {
            String query = "SELECT id, username, status FROM `userdetails`";
            PreparedStatement statement = productsFrames.conn().prepareStatement(query);
            ResultSet res = statement.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("User ID");
            model.addColumn("Username");
            model.addColumn("Status");

            while (res.next()) {
                int id = res.getInt("id");
                String username = res.getString("username");
                String status = res.getString("status");

                model.addRow(new Object[]{id, username, status});
            }

            userListTable.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void callData() {
        try {
            String query = "SELECT * FROM `loginHistory`";
            PreparedStatement statement = productsFrames.conn().prepareStatement(query);
            ResultSet res = statement.executeQuery();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("user id");
            model.addColumn("username");
            model.addColumn("history id");
            while (res.next()) {
                int id = res.getInt("id");
                String username = res.getString("username");
                int historyId = res.getInt("historyId");

                model.addRow(new Object[]{id, username, historyId});
            }
            myTable1.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Method to load reports from DB into the table
    private void loadReports() {
        try {
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:5050/mydatabase", "root", "");
            String query = "SELECT * FROM `reportlist`";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Description");
            model.addColumn("Type");

            while (rs.next()) {
                int id = rs.getInt("id");
                String type = rs.getString("reportMsg");
                String description = rs.getString("reportType");
                model.addRow(new Object[]{id, type, description});
            }

            reportListTable.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading reports: " + e.getMessage());
        }
    }

    String credential;

    public adminPanel(String credential) {
        initComponents();
        this.credential = credential;
        setLocationRelativeTo(null);
        callData();

        loginHistoryLabel1.setVisible(false);
        userListLabel1.setVisible(false);
        userListPanel.setVisible(false);
        callUserList();
        loadReports();
        reportListPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportListPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reportListTable = new javax.swing.JTable();
        reportMsg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        userListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userListTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        loginHistoryLabel = new javax.swing.JLabel();
        reportList = new javax.swing.JLabel();
        reportList1 = new javax.swing.JLabel();
        userListLabel = new javax.swing.JLabel();
        userListLabel1 = new javax.swing.JLabel();
        loginHistoryLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        loginHistoryPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reportListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportListTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(reportListTable);

        reportListPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 340, 250));

        reportMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportMsg.setForeground(new java.awt.Color(255, 255, 255));
        reportListPanel.add(reportMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 170, 250));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Report User List");
        reportListPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1) (1).png"))); // NOI18N
        reportListPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 910, 450));

        getContentPane().add(reportListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 590, 330));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dashboard");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-back-48.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 36));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-exit-50 (1).png"))); // NOI18N
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 40));

        userListPanel.setVerifyInputWhenFocusTarget(false);
        userListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userListTable);

        userListPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 250));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1) (1).png"))); // NOI18N
        userListPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        getContentPane().add(userListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 570, 350));
        userListPanel.getAccessibleContext().setAccessibleName("");

        loginHistoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginHistoryLabel.setForeground(new java.awt.Color(51, 255, 51));
        loginHistoryLabel.setText("           Login History");
        loginHistoryLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginHistoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHistoryLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginHistoryLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginHistoryLabelMouseExited(evt);
            }
        });
        getContentPane().add(loginHistoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        reportList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportList.setForeground(new java.awt.Color(0, 255, 0));
        reportList.setText("        Report Messages");
        reportList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportListMouseExited(evt);
            }
        });
        getContentPane().add(reportList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 50));

        reportList1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportList1.setForeground(new java.awt.Color(0, 255, 0));
        reportList1.setText("        Report Messages");
        reportList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportList1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportList1MouseExited(evt);
            }
        });
        getContentPane().add(reportList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 50));

        userListLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userListLabel.setForeground(new java.awt.Color(0, 255, 0));
        userListLabel.setText("              User List");
        userListLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userListLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userListLabelMouseExited(evt);
            }
        });
        getContentPane().add(userListLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        userListLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userListLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(userListLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        loginHistoryLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginHistoryLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginHistoryLabel1MouseExited(evt);
            }
        });
        getContentPane().add(loginHistoryLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1).png"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel22.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 290, 450));

        loginHistoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("login History");
        loginHistoryPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("delete history");
        loginHistoryPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, 30));

        myTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(myTable1);

        loginHistoryPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 420, 230));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_icons8-delete-48.png"))); // NOI18N
        jLabel6.setText("delete history");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        loginHistoryPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 110, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1) (1).png"))); // NOI18N
        loginHistoryPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        getContentPane().add(loginHistoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 590, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 910, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            String query = "SELECT status FROM `userdetails` WHERE `username` = ?";
            PreparedStatement statement = productsFrames.conn().prepareStatement(query);
            statement.setString(1, credential);
            ResultSet res = statement.executeQuery();

            if (res.next() && res.getString("status").equals("admin")) {
                new dashboardAdmin(credential).setVisible(true);
            } else {
                new dashboardEmployee(credential).setVisible(true);
            }

            this.dispose();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        DefaultTableModel model = (DefaultTableModel) myTable1.getModel();
        int SelectedRow = myTable1.getSelectedRow();
        int SelectedColumn = myTable1.getSelectedColumn();

        int confirmation = JOptionPane.showConfirmDialog(this, "are you sure?");

        if (confirmation == 0) {
            int value = (Integer) model.getValueAt(SelectedRow, 2);
            try {
                String query = "DELETE FROM `loginhistory` WHERE `historyId` = ?";
                PreparedStatement statement = productsFrames.conn().prepareStatement(query);
                statement.setInt(1, value);
                statement.executeUpdate();

                callData();

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void userListLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListLabel1MouseEntered

    }//GEN-LAST:event_userListLabel1MouseEntered

    private void loginHistoryLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginHistoryLabel1MouseExited

    private void loginHistoryLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryLabel1MouseEntered

    }//GEN-LAST:event_loginHistoryLabel1MouseEntered

    private void loginHistoryLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryLabelMouseEntered
        loginHistoryLabel1.setVisible(true);
        loginHistoryLabel1.setOpaque(true);
        loginHistoryLabel1.setBackground(Color.white);
    }//GEN-LAST:event_loginHistoryLabelMouseEntered

    private void userListLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListLabelMouseEntered
        userListLabel1.setVisible(true);
        userListLabel1.setOpaque(true);
        userListLabel1.setBackground(Color.white);
    }//GEN-LAST:event_userListLabelMouseEntered

    private void userListLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListLabelMouseExited
        userListLabel1.setVisible(false);
    }//GEN-LAST:event_userListLabelMouseExited

    private void loginHistoryLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryLabelMouseExited
        loginHistoryLabel1.setVisible(false);
    }//GEN-LAST:event_loginHistoryLabelMouseExited

    private void loginHistoryLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryLabelMouseClicked
        loginHistoryPanel.setVisible(true);
        loginHistoryLabel.setOpaque(true);
        loginHistoryLabel.setBackground(Color.white);

        userListLabel.setBackground(null);
        userListLabel.setOpaque(false);
        userListPanel.setVisible(false);
        reportListPanel.setVisible(false);
        reportList.setBackground(null);
        reportList.setOpaque(false);
    }//GEN-LAST:event_loginHistoryLabelMouseClicked

    private void userListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListLabelMouseClicked
        userListPanel.setVisible(true);
        userListLabel.setOpaque(true);
        userListLabel.setBackground(Color.white);

        loginHistoryLabel.setBackground(null);
        loginHistoryLabel.setOpaque(false);
        loginHistoryPanel.setVisible(false);
        reportListPanel.setVisible(false);
        reportList.setBackground(null);
        reportList.setOpaque(false);
    }//GEN-LAST:event_userListLabelMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered

    }//GEN-LAST:event_exitBtnMouseEntered

    private void reportListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportListMouseClicked
        reportListPanel.setVisible(true);
        reportList.setOpaque(true);
        reportList.setBackground(Color.white);

        loginHistoryLabel.setBackground(null);
        loginHistoryLabel.setOpaque(false);
        loginHistoryPanel.setVisible(false);

        userListLabel.setBackground(null);
        userListLabel.setOpaque(false);
    }//GEN-LAST:event_reportListMouseClicked

    private void reportListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportListMouseEntered
        reportList1.setVisible(true);
        reportList1.setOpaque(true);
        reportList1.setBackground(Color.white);
    }//GEN-LAST:event_reportListMouseEntered

    private void reportListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportListMouseExited
        reportList1.setVisible(false);
        reportList1.setOpaque(true);
        reportList1.setBackground(Color.white);
    }//GEN-LAST:event_reportListMouseExited

    private void reportList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reportList1MouseClicked

    private void reportList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportList1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reportList1MouseEntered

    private void reportList1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportList1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reportList1MouseExited

    private void reportListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportListTableMouseClicked
        int selectedRow = reportListTable.getSelectedRow();
        if (selectedRow != -1) {
            // Assuming description is in column 2 (index 2)
            String description = reportListTable.getValueAt(selectedRow, 1).toString();
            reportMsg.setText(description);
        }
    }//GEN-LAST:event_reportListTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPanel("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel loginHistoryLabel;
    private javax.swing.JLabel loginHistoryLabel1;
    private javax.swing.JPanel loginHistoryPanel;
    private javax.swing.JTable myTable1;
    private javax.swing.JLabel reportList;
    private javax.swing.JLabel reportList1;
    private javax.swing.JPanel reportListPanel;
    private javax.swing.JTable reportListTable;
    private javax.swing.JLabel reportMsg;
    private javax.swing.JLabel userListLabel;
    private javax.swing.JLabel userListLabel1;
    private javax.swing.JPanel userListPanel;
    private javax.swing.JTable userListTable;
    // End of variables declaration//GEN-END:variables
}
