/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication13;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author borag
 */
public class dashboardEmployee extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    String credential;

    public dashboardEmployee(String credential) {
        initComponents();
        setLocationRelativeTo(null);
        this.credential = credential;
        greetLabel.setText(greetLabel.getText() + " "+ credential.toUpperCase() + " " + ":)");
        System.out.print(credential);
        settingPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        reportHighlight = new javax.swing.JLabel();
        logoutHighlight = new javax.swing.JLabel();
        settingClose = new javax.swing.JLabel();
        settingBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        greetLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingPanel.setBackground(new java.awt.Color(255, 255, 255));
        settingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportHighlight.setBackground(new java.awt.Color(255, 0, 0));
        reportHighlight.setForeground(new java.awt.Color(255, 51, 51));
        reportHighlight.setText("    report");
        reportHighlight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportHighlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportHighlightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportHighlightMouseExited(evt);
            }
        });
        settingPanel.add(reportHighlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 60, 30));

        logoutHighlight.setText("    Logout");
        logoutHighlight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutHighlight.setFocusCycleRoot(true);
        logoutHighlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutHighlightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutHighlightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutHighlightMouseExited(evt);
            }
        });
        settingPanel.add(logoutHighlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 30));

        settingClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-chevron-down-26.png"))); // NOI18N
        settingClose.setAlignmentX(0.5F);
        settingClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingCloseMouseClicked(evt);
            }
        });
        settingPanel.add(settingClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 30, 20));

        getContentPane().add(settingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 60, 120));

        settingBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\borag\\Downloads\\icons8-chevron-up-30.png")); // NOI18N
        settingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingBtnMouseClicked(evt);
            }
        });
        settingBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                settingBtnKeyPressed(evt);
            }
        });
        getContentPane().add(settingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 30, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sales Tracker System");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 20));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-exit-50 (1).png"))); // NOI18N
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 40));

        greetLabel.setBackground(new java.awt.Color(255, 255, 255));
        greetLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        greetLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetLabel.setText("Welcome");
        getContentPane().add(greetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Inventory System");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_ecoshift-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-sales-100.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-inventory-100.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 110, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new productsFrames(credential).setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new SalesTrackerSystem(credential).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void settingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingBtnMouseClicked
        settingPanel.setVisible(true);
    }//GEN-LAST:event_settingBtnMouseClicked

    private void settingBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_settingBtnKeyPressed
        settingPanel.setVisible(true);
    }//GEN-LAST:event_settingBtnKeyPressed

    private void reportHighlightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportHighlightMouseEntered
        reportHighlight.setOpaque(true);
        reportHighlight.setBackground(Color.red);
    }//GEN-LAST:event_reportHighlightMouseEntered

    private void reportHighlightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportHighlightMouseExited
        reportHighlight.setBackground(null);
    }//GEN-LAST:event_reportHighlightMouseExited

    private void logoutHighlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutHighlightMouseClicked

        int result = JOptionPane.showConfirmDialog(
            null,
            "are you sure you want to continue?",
            "confimation",
            JOptionPane.YES_NO_OPTION
        );

        if (result == JOptionPane.YES_OPTION) {
            new loginFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutHighlightMouseClicked

    private void logoutHighlightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutHighlightMouseEntered
        logoutHighlight.setOpaque(true);
        logoutHighlight.setBackground(Color.red);
    }//GEN-LAST:event_logoutHighlightMouseEntered

    private void logoutHighlightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutHighlightMouseExited
        logoutHighlight.setBackground(null);
    }//GEN-LAST:event_logoutHighlightMouseExited

    private void settingCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingCloseMouseClicked
        settingPanel.setVisible(false);
    }//GEN-LAST:event_settingCloseMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered

    }//GEN-LAST:event_exitBtnMouseEntered


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardEmployee("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel greetLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logoutHighlight;
    private javax.swing.JLabel reportHighlight;
    private javax.swing.JLabel settingBtn;
    private javax.swing.JLabel settingClose;
    private javax.swing.JPanel settingPanel;
    // End of variables declaration//GEN-END:variables
}
