/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication13;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author borag
 */
public class loginFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
    public void passwordFocused() {
        if (jPasswordField1.getPassword().length == 0) {
            passwordLabel.setVisible(false);
            passwordLabel1.setVisible(true);
        } else {
            passwordLabel.setVisible(true);
            passwordLabel1.setVisible(false);
        }
    }

    public void usernameFocused() {
        if (jTextField2.getText().length() == 0) {
            usernameLabel.setVisible(true);
            usernameLabel1.setVisible(false);
        } else {
            usernameLabel.setVisible(false);
            usernameLabel1.setVisible(true);
        }

    }

    public void addListenerToFocus(JTextComponent textField) {
        textField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                passwordFocused();
                usernameFocused();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                passwordFocused();
                usernameFocused();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                passwordFocused();
                usernameFocused();
            }
        });

    }

    public loginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        hideEye.setVisible(false);
        textFieldPass.setVisible(false);
        addListenerToFocus(jPasswordField1);
        addListenerToFocus(jTextField2);
        usernameLabel.setVisible(false);
        passwordLabel.setVisible(false);
        getContentPane().setComponentZOrder(jLabel5, getContentPane().getComponentCount() - 1);

     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel6 = new javax.swing.JLabel();
        showEye = new javax.swing.JLabel();
        hideEye = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        usernameLabel1 = new javax.swing.JLabel();
        textFieldPass = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        exitBtn = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_icons8-eye-24.png"))); // NOI18N
        showEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showEyeMouseClicked(evt);
            }
        });
        getContentPane().add(showEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 30, 30));

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_icons8-invisible-30 (3).png"))); // NOI18N
        hideEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hideEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideEyeMouseClicked(evt);
            }
        });
        getContentPane().add(hideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 30));

        usernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 137, -1, -1));

        passwordLabel1.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel1.setText("password");
        getContentPane().add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 206, 60, -1));

        usernameLabel1.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel1.setText("Username");
        getContentPane().add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        textFieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPassFocusLost(evt);
            }
        });
        textFieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldPassMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFieldPassMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFieldPassMousePressed(evt);
            }
        });
        getContentPane().add(textFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 230, 30));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 230, 30));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/icons8-exit-50 (1).png"))); // NOI18N
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 40));

        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setText("password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/ecoshift-removebg-preview_50.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 80));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 230, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("doesn't have account? SIGNUP");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 200, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign in");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 210, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/resizecom_background ecoShift (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

    }//GEN-LAST:event_jPasswordField1ActionPerformed


    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void showEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showEyeMouseClicked
        showEye.setVisible(false);
        hideEye.setVisible(true);
        textFieldPass.setVisible(true);
        textFieldPass.setText(jPasswordField1.getText());
        jPasswordField1.setVisible(false);
    }//GEN-LAST:event_showEyeMouseClicked

    private void hideEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideEyeMouseClicked
        showEye.setVisible(true);
        hideEye.setVisible(false);
        textFieldPass.setVisible(false);
        jPasswordField1.setText(textFieldPass.getText());
        jPasswordField1.setVisible(true);
    }//GEN-LAST:event_hideEyeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new registerFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:5050/mydatabase",
                    "root",
                    "");
            String query = "SELECT * FROM `userdetails` WHERE username = ? AND password = ?";
            PreparedStatement statement = con.prepareStatement(query);

            statement.setString(1, jTextField2.getText());
            if (jPasswordField1.getText().isEmpty()) {
                statement.setString(2, textFieldPass.getText());
            } else {
                statement.setString(2, jPasswordField1.getText());

            }
            ResultSet res = statement.executeQuery();

            if (res.next()) {

                String status = res.getString("status");
                System.out.print(status);
                if (status.equals("employee")) {
                    dashboardEmployee dashFrame = new dashboardEmployee(res.getString("username"));
                    this.dispose();
                    dashFrame.setVisible(true);
                } else {
                    dashboardAdmin dashAdmin = new dashboardAdmin(res.getString("username"));
                    this.dispose();
                    dashAdmin.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(this, "can't log you in");
            }

            String historyQuery = "INSERT INTO `loginhistory`(`id`, `username`) VALUES (?,?)";
            PreparedStatement historyStatement = con.prepareStatement(historyQuery);
            historyStatement.setInt(1, res.getInt("id"));
            historyStatement.setString(2, res.getString("username"));
            historyStatement.execute();

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void textFieldPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPassMousePressed
        passwordLabel1.setVisible(false);
    }//GEN-LAST:event_textFieldPassMousePressed

    private void textFieldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPassMouseClicked
    }//GEN-LAST:event_textFieldPassMouseClicked

    private void textFieldPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPassMouseExited

    }//GEN-LAST:event_textFieldPassMouseExited

    private void textFieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPassFocusLost

    }//GEN-LAST:event_textFieldPassFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel hideEye;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel showEye;
    private javax.swing.JTextField textFieldPass;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
