/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication13;

/**
 *
 * @author borag
 */
public class loadingFrame extends javax.swing.JFrame {

    /**
     * Creates new form loadingFrame
     */
    public loadingFrame() {
        initComponents();
        setLocationRelativeTo(null);

        new Thread(() -> {
            try {
                for (int i = 0; i < 100; i++) {
                    Thread.sleep(100);
                    int numberOfChar = loadingHeader.getText().length();
                    int numberOfDot = loadingHeader.getText().replace(".", "").length();
                    int totalChar = numberOfChar - numberOfDot;
                    if (totalChar == 3) {
                        loadingHeader.setText("Loading data");
                    }
                    loadingHeader.setText(loadingHeader.getText() + ".");
                }
            } catch (Exception e) {
                e.printStackTrace();
            };
        }).start();

        new Thread(() -> {
            try {
                for (int i = 0; i < 100; i++) {
                    Thread.sleep(50);
                }
                loginFrame prodFrame = new loginFrame();
                prodFrame.setVisible(true);
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            };
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loadingHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/background_ecoShift_516x300.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(490, 300));

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingHeader.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        loadingHeader.setText("Loading data");
        getContentPane().add(loadingHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 90, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/ecoShiftLoading-unscreen-ezgif.com-resize (2).gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/ecoshift-removebg-preview_50.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication13/background_ecoShift_516x300.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel loadingHeader;
    // End of variables declaration//GEN-END:variables
}
